import test from 'node:test';import assert from 'node:assert/strict';
import {Simulation,capacity} from './simulation.mjs';
const tick=(g,seconds,serve=false)=>{for(let i=0;i<seconds*20;i++){if(serve)g.serve();g.tick(.05)}};
test('invalid orders do not partially spend money',()=>{const g=new Simulation(()=>.5);assert.throws(()=>g.open([1000,1000,1000,1000],[1,1,1],150));assert.equal(g.state.cash,2000);assert.deepEqual(g.state.inventory,[0,0,0,0]);assert.throws(()=>g.open([1,1,1,1],[0,1,1],150));assert.equal(g.phase,'setup')});
test('sale requires a player action; duplicate clicks cannot double charge',()=>{const g=new Simulation(()=>.5);g.open([10,10,10,10],[1,1,1],100);tick(g,7);assert.equal(g.queue[0]?.state,'waiting');const cash=g.state.cash;assert.equal(g.stats.sold,0);assert.equal(g.serve(),true);assert.equal(g.serve(),false);tick(g,1.4);assert.equal(g.stats.sold,1);assert.equal(g.state.cash,cash+100);assert.deepEqual(g.state.inventory,[9,9,9,9]);assert.equal(new Set(g.queue.map(p=>p.id)).size,g.queue.length)});
test('pause freezes movement, cooking and the clock',()=>{const g=new Simulation(()=>.5);g.open([10,10,10,10],[1,1,1],100);tick(g,7);g.serve();g.paused=true;const before=JSON.stringify(g);tick(g,20,true);assert.equal(JSON.stringify(g),before)});
test('expensive lemonade is rejected with no income',()=>{const g=new Simulation(()=>.5);g.open([10,10,10,10],[1,1,1],500);tick(g,12,true);assert.ok(g.stats.rejected>0);assert.equal(g.stats.revenue,0);assert.deepEqual(g.state.inventory,[10,10,10,10])});
test('unserved customers time out and the day finishes',()=>{const g=new Simulation(()=>.5);g.open([10,10,10,10],[1,1,1],100);tick(g,140);assert.equal(g.phase,'summary');assert.ok(g.stats.impatient>0);assert.equal(g.stats.sold,0);assert.equal(g.queue.length,0)});
test('a complete played day preserves cash accounting and never oversells',()=>{const g=new Simulation(()=>.5);g.open([3,3,3,3],[1,1,1],100);tick(g,140,true);assert.equal(g.phase,'summary');assert.equal(g.stats.sold,3);assert.equal(capacity(g.state.inventory,g.recipe),0);assert.equal(g.state.cash,2000-g.stats.cost+g.stats.revenue);assert.equal(g.stats.profit,g.stats.revenue-g.stats.cost);const cash=g.state.cash;g.next();assert.equal(g.phase,'setup');assert.equal(g.state.day,2);assert.equal(g.state.cash,cash);assert.deepEqual(g.state.inventory,[0,0,0,0]);g.reset();assert.equal(g.state.cash,2000);assert.equal(g.state.day,1)});
